# Generated by Django 5.0 on 2023-12-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.TextField(max_length=500),
        ),
    ]
